name: study_up
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.1.0
  flutter_localizations:
    sdk: flutter
  # Estado
  flutter_riverpod: ^2.4.0
  # Firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.1.0
  google_sign_in: ^6.2.1
  # UI
  google_fonts: ^6.2.0
  intl: ^0.20.2
  table_calendar: ^3.0.8
  timezone: ^0.9.4
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
